### ISSUE TITLE
Не отображается игра указанного жанра, в которую играли больше всего

### ISSUE THREAD

**Issue by w4ssel** [dashaboog/Group-project#10]
# Описание
Метод **mostPlayerByGenre**  не возвращает игру указанного жанра, в которую играли больше всего

# Локация дефекта
https://github.com/dashaboog/Group-project/blob/e2523db709cf01401b95aaf862e8bea1ac4adb75/src/main/java/ru/netology/Player.java#L59-L61

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/dashaboog/Group-project/blob/60338f5f8b2cb0725540dbf5d9993dbbea954cb4/src/test/java/ru/netology/PlayerTest.java#L80) в IDEA.
2. Запустить готовый тест `shouldShowGamePlayedMost`
3. Посмотреть результат теста в консоли

*Ожидаемый результат:* Тест проходит, выводится игра с бОльшим игровым временем
*Фактический результат:* Тест не проходит, выводится `null`

# Скриншот
![image](https://user-images.githubusercontent.com/112583292/216988481-d5ac45af-9d6c-41ca-bf2e-fcd7cf25e00b.png)

# Окружение

* **Операционная система:** Windows 11 version 21H2 build 22000.1455
* **IDE:** IntelliJ IDEA 2022.2.4 (Community Edition)
* **Java:** OpenJDK 11

**Comment by dashaboog** [comment]
Код дописан, тесты проходят.
