### ISSUE TITLE
Не суммируется время игрока, проведенное в играх одного жанра

### ISSUE THREAD

**Issue by w4ssel** [dashaboog/Group-project#7]
# Описание
Метод **sumGenre**  не суммирует время игрока, проведенное в играх одного указанного жанра

# Локация дефекта
https://github.com/dashaboog/Group-project/blob/e2523db709cf01401b95aaf862e8bea1ac4adb75/src/main/java/ru/netology/Player.java#L45-L55

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/dashaboog/Group-project/blob/60338f5f8b2cb0725540dbf5d9993dbbea954cb4/src/test/java/ru/netology/PlayerTest.java#L30) в IDEA.
2. Запустить готовый тест `shouldSumGenreIfGamesSameGenre`
3. Посмотреть результат теста в консоли

*Ожидаемый результат:* Тест проходит, время суммируется
*Фактический результат:* Тест не проходит, время не суммируется, выводится 0 

# Скриншот
![image](https://user-images.githubusercontent.com/112583292/216981080-59bbed28-afbc-43d0-8794-773e9b5d68b6.png)

# Окружение

* **Операционная система:** Windows 11 version 21H2 build 22000.1455
* **IDE:** IntelliJ IDEA 2022.2.4 (Community Edition)
* **Java:** OpenJDK 11

**Comment by dashaboog** [comment]
Ошибка исправлена за счёт исправления ошибки в playedTime. Тесты проходят.
