### ISSUE TITLE
Не суммируется время игрока, проведенное в одной и той же игре определенного жанра

### ISSUE THREAD

**Issue by w4ssel** [dashaboog/Group-project#8]
# Описание
Метод **play**  не суммирует время игрока, проведенное в одной и той же игре указанного жанра (игрок переигрывает в игру)

# Локация дефекта
https://github.com/dashaboog/Group-project/blob/60338f5f8b2cb0725540dbf5d9993dbbea954cb4/src/main/java/ru/netology/Player.java#L33-L41

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/dashaboog/Group-project/blob/60338f5f8b2cb0725540dbf5d9993dbbea954cb4/src/test/java/ru/netology/PlayerTest.java#L44) в IDEA.
2. Запустить готовый тест `shouldSumGenreIfGameReplay`
3. Посмотреть результат теста в консоли

*Ожидаемый результат:* Тест проходит, время суммируется
*Фактический результат:* Тест не проходит, время не суммируется, выводится 0

# Скриншот
![image](https://user-images.githubusercontent.com/112583292/216981619-8891f007-2eb1-4ca5-87a4-1851270fce27.png)

# Окружение

* **Операционная система:** Windows 11 version 21H2 build 22000.1455
* **IDE:** IntelliJ IDEA 2022.2.4 (Community Edition)
* **Java:** OpenJDK 11

**Comment by dashaboog** [comment]
Время добавлено.
