### ISSUE TITLE
Не выводится исключение, если игра не установлена

### ISSUE THREAD

**Issue by w4ssel** [dashaboog/Group-project#9]
# Описание
Метод **play**  не выкидывает исключение, если игра не установлена

# Локация дефекта
https://github.com/dashaboog/Group-project/blob/60338f5f8b2cb0725540dbf5d9993dbbea954cb4/src/main/java/ru/netology/Player.java#L33-L41

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/dashaboog/Group-project/blob/player/src/test/java/ru/netology/PlayerTest.java#L71) в IDEA.
2. Запустить готовый тест `shouldThrowExceptionIfGameNotInstalled`
3. Посмотреть результат теста в консоли

*Ожидаемый результат:* Тест проходит, выкидывается исключение
*Фактический результат:* Тест не проходит, не выкидывается исключение

# Скриншот
![image](https://user-images.githubusercontent.com/112583292/216986688-a6502ac0-b46a-4263-b015-1ed6b71a6ed7.png)

# Окружение

* **Операционная система:** Windows 11 version 21H2 build 22000.1455
* **IDE:** IntelliJ IDEA 2022.2.4 (Community Edition)
* **Java:** OpenJDK 11

**Comment by dashaboog** [comment]
RuntimeException добавлена.
